### ISSUE TITLE
How do I use bastion

### ISSUE THREAD

**Issue by pvprangergod** [DevotedMC/Bastion#42]
I made a kit that gives a bastion block, when I place it somewhere the console says:
[Bastion] Pending a bastion at Location{world=CraftWorld{name=world},x=393.0,y=71.0,z=690.0,pitch=0.0,yaw=0.0}
I use /bsi and it says there is "No Bastion Block"
I put the warmup time to 1 and still it says "No Bastion Block"

**Comment by ProgrammerDan** [comment]
A bastion is never a bastion unless reinforced (using Citadel reinforcements)
