### ISSUE TITLE
BSI prints output twice

### ISSUE THREAD

**Issue by Diet-Cola** [DevotedMC/Bastion#8]
Steps to repro: 
1. /bsi
2. Right click ground or bastion block

**Comment by ProgrammerDan** [comment]
Where you on a server as Operator?

**Comment by Diet-Cola** [comment]
Nope, happens on devoted & civcraft.

**Comment by ProgrammerDan** [comment]
Yay

**Comment by ProgrammerDan** [comment]
Sure you aren't doubleclickng somehow? hmm.

**Comment by Diet-Cola** [comment]
[Small video of it on Devoted](https://www.youtube.com/watch?v=Ej4JhtXRmwk&feature=youtu.be)

**Comment by ProgrammerDan** [comment]
Fixed in #38
